name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set ENV variables
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
          echo "DOCKER_TAG=paper_trail:$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Expose .env to steps
        run: |
          sed -i $(echo "s/\$DOCKER_TAG/$DOCKER_TAG/g") .env
          cat .env >> $GITHUB_ENV
      - name: Docker-compose pull
        run: docker-compose pull
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.HUB_USERNAME }}/${{ env.DOCKER_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Docker-compose up
        run: docker-compose -f docker-compose.yaml up -d
      - name: Execute tests
        run: |
          docker-compose exec -T paper_trail mix test test/paper_trail
          docker-compose run paper_trail mix test test/version
          docker-compose run paper_trail mix test test/uuid
          STRING_TEST=true docker-compose run paper_trail mix test test/uuid
